trigger: none
  # batch: 'true'
  # branches:
  #   include: [ master ]
  # tags:
  #   exclude: [ NoBuild ]


stages:
# P0 - Sub Deploy (G0)
- stage: P0_Sub
  variables:
    APP : ADF
    ENV: P0
    PREFIX : AZC1
  jobs:
  - job: RG_RBAC
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'ADF_AZC1-ADF-RG-G0'
        ScriptType: 'FilePath'
        ScriptPath: 'ADF/release-az/AzDeploy.ps1'
        ScriptArguments: '-app $(app) -env $(env) -Prefix $(prefix) -stage "sub-InitialRG" -FullUpload'
        FailOnStandardError: true
        azurePowerShellVersion: 'LatestVersion'

# P0 - RG Deploy
- stage: P0_RG
  variables:
    APP : ADF
    ENV: P0
    PREFIX : AZC1
  jobs:
  - job: Initial_P0
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'ADF_AZC1-ADF-RG-P0'
        ScriptType: 'FilePath'
        ScriptPath: 'ADF/release-az/AzDeploy.ps1'
        ScriptArguments: '-app $(app) -env $(env) -Prefix $(Prefix) -stage "ALL"'
        FailOnStandardError: true
        azurePowerShellVersion: 'LatestVersion'
