
GET https://management.azure.com/subscriptions/1f0713fe-9b12-4c8f-ab0c-26aba7aaa3e5/resourceGroups/AZC1-BRW-ABC-RG-S1/providers/Microsoft.Storage/storageAccounts/azc1brwabcs1sadiag/blobservices?api-version=2020-08-01-preview
Authorization: {{Bearer}}