trigger: none

parameters:
  - name: STAGE
    displayName: Deployment Stage
    type: string
    default: 00-ALL-SUB
    values:
      - 00-ALL-SUB

  - name: CN
    displayName: Deployment Stage
    type: string
    default: '.'
    values:
      - '.'


variables:
  ORG: PE
  APP: GW

  PREFIX: ACU1
  ENV: G0

  ADOProject: ADO_ADF
  PREFIXPRIMARY: ACU1
  APPPRIMARY: GW
  UAI: 0

stages:
  - stage: Deploy_All_${{ variables.PREFIX }}_${{ variables.ORG }}_${{ variables.APP }}_RG_${{ variables.ENV }}
    jobs:
      - template: ..\..\..\.ado\ado-pipelines-STAGE.yml
        parameters:
          ORG:        ${{ variables.ORG }}
          APP:        ${{ variables.APP }}
          APPPRIMARY: ${{ variables.APPPRIMARY}}
          PREFIX:     ${{ variables.PREFIX }}
          ENV:        ${{ variables.ENV }}
          SP:         ${{ variables.ADOProject }}_${{ variables.PREFIX }}-${{ variables.ORG }}-${{ variables.APP }}-RG
          SPG0:       ${{ variables.ADOProject }}_${{ variables.PREFIXPRIMARY }}-${{ variables.ORG }}-${{ variables.APPPRIMARY }}-RG
          STAGE:      ${{ parameters.STAGE }}
          CN:         ${{ parameters.CN }}
          UAI:        ${{ variables.UAI }}
          POOLPrefix: 'aeu2'
