###
GET https://awcu-pe-pst-d3-apim01.psthing.com/MyApi01/ HTTP/1.1
Ocp-Apim-Subscription-Key: {{subkey}}
Ocp-Apim-Trace: true

###
GET http://awcu-pe-pst-d3-apim01.psthing.com/echo/resource?param1=sample HTTP/1.1
Ocp-Apim-Subscription-Key: {{subkey}}
Ocp-Apim-Trace: true

