# This is a basic workflow to help you get started with Actions

name:
  Deploy_ACU1_BRW_PSO_RG_M0
  # Triggers the workflow on push or pull request events but only for the main branch
  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  workflow_dispatch:

env:
  APP: PSO
  ENV: M0
  PREFIX: ACU1

jobs:
  EnvironmentDeploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Add wait on concurrent workflows executing via https://github.com/marketplace/actions/action-turnstyle
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.ACU1_BRW_PSO_RG_M0}}
          enable-AzPSSession: true

      - name: G0_Sub
        uses: Azure/powershell@v1
        with:
          inlineScript: ./ADF/release-az/AzDeploy.ps1 -app $env:app -env $env:env -Prefix $env:prefix -stage "sub-InitialRG" -FullUpload
          azPSVersion: latest

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.ACU1_BRW_PSO_RG_M0}}
          enable-AzPSSession: true

      - name: M0_RG
        uses: Azure/powershell@v1
        with:
          inlineScript: ./ADF/release-az/AzDeploy.ps1 -app $env:app -env $env:env -Prefix $env:prefix -stage "ALL"
          azPSVersion: latest
